Regression Model with sklearn

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/ybifoundation/Dataset/main/Fish.csv')

In [7]:
df.head()

Category Species  Weight   Height   Width  Length1  Length2  Length3
0         1   Bream   242.0  11.5200  4.0200     23.2     25.4     30.0
1         1   Bream   290.0  12.4800  4.3056     24.0     26.3     31.2
2         1   Bream   340.0  12.3778  4.6961     23.9     26.5     31.1
3         1   Bream   363.0  12.7300  4.4555     26.3     29.0     33.5
4         1   Bream   430.0  12.4440  5.1340     26.5     29.0     34.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Category  159 non-null    int64  
 1   Species   159 non-null    object 
 2   Weight    159 non-null    float64
 3   Height    159 non-null    float64
 4   Width     159 non-null    float64
 5   Length1   159 non-null    float64
 6   Length2   159 non-null    float64
 7   Length3   159 non-null    float64
dtypes: float64(6), int64(1), object(1)
memory usage: 10.1+ KB


In [5]:
df.describe()

Category       Weight      Height       Width     Length1  \
count  159.000000   159.000000  159.000000  159.000000  159.000000   
mean     3.264151   398.326415    8.970994    4.417486   26.247170   
std      1.704249   357.978317    4.286208    1.685804    9.996441   
min      1.000000     0.000000    1.728400    1.047600    7.500000   
25%      2.000000   120.000000    5.944800    3.385650   19.050000   
50%      3.000000   273.000000    7.786000    4.248500   25.200000   
75%      4.500000   650.000000   12.365900    5.584500   32.700000   
max      7.000000  1650.000000   18.957000    8.142000   59.000000   

          Length2     Length3  
count  159.000000  159.000000  
mean    28.415723   31.227044  
std     10.716328   11.610246  
min      8.400000    8.800000  
25%     21.000000   23.150000  
50%     27.300000   29.400000  
75%     35.500000   39.650000  
max     63.400000   68.000000

In [8]:
df.shape

(159, 8)

In [9]:
df.columns

Index(['Category', 'Species', 'Weight', 'Height', 'Width', 'Length1',
       'Length2', 'Length3'],
      dtype='object')

In [10]:
y = df['Weight']

In [11]:
y.shape

(159,)

In [12]:
y

0      242.0
1      290.0
2      340.0
3      363.0
4      430.0
       ...  
154     12.2
155     13.4
156     12.2
157     19.7
158     19.9
Name: Weight, Length: 159, dtype: float64

In [13]:
X = df[['Height', 'Width', 'Length1', 'Length2', 'Length3']]

In [14]:
X.shape

(159, 5)

In [15]:
X

Height   Width  Length1  Length2  Length3
0    11.5200  4.0200     23.2     25.4     30.0
1    12.4800  4.3056     24.0     26.3     31.2
2    12.3778  4.6961     23.9     26.5     31.1
3    12.7300  4.4555     26.3     29.0     33.5
4    12.4440  5.1340     26.5     29.0     34.0
..       ...     ...      ...      ...      ...
154   2.0904  1.3936     11.5     12.2     13.4
155   2.4300  1.2690     11.7     12.4     13.5
156   2.2770  1.2558     12.1     13.0     13.8
157   2.8728  2.0672     13.2     14.3     15.2
158   2.9322  1.8792     13.8     15.0     16.2

[159 rows x 5 columns]

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3 , random_state =  2529)

In [18]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((111, 5), (48, 5), (111,), (48,))

In [19]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [20]:
model.fit(X_train, y_train)

LinearRegression()

In [21]:
model.coef_

array([ 29.86430261,   2.25937742,  58.33792721,   8.53385903,
       -36.1520994 ])

In [24]:
model.intercept_

-519.2833724383818

In [26]:
y_pred = model.predict(X_test)
y_pred.shape

(48,)

In [28]:
y_pred

array([ 485.76826299,  502.24720857,   94.72381964,  876.5711712 ,
        184.0789176 ,  219.30130488,  322.32532246,  376.22325991,
        372.35730485, -182.67537078, -160.60486837,  454.33586185,
        159.59755829,  843.48525226,  587.21680573,  299.53521445,
        597.72950823,  197.14605397,  639.89046741,   91.20067876,
        150.95424753, -103.08320574,  627.19712753,  795.69176861,
        814.68732975, -204.1496511 ,  329.98746856,  715.89288013,
        359.75634357,  792.3243925 ,  532.7036706 ,  552.00832342,
        433.48472727,  687.61750267, -204.76362537,  932.53668294,
        810.74234216,  -80.06217174,  284.36287887,  907.08036021,
        642.5828335 ,  959.33848223,  675.28792291,  718.86305458,
        623.89849226,  376.48346981,  530.83828119,  -86.2357066 ])

In [29]:
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, mean_absolute_error,r2_score

In [30]:
mean_squared_error(y_test, y_pred)

16397.344524411383

In [31]:
mean_absolute_percentage_error(y_test, y_pred)

2.5082853471600237

In [32]:
mean_absolute_error(y_test, y_pred)

103.02952922678541

In [33]:
r2_score(y_test, y_pred)

0.8349141424416877

In [34]:
df_new = df.sample(1)

In [35]:
df_new

Category Species  Weight  Height  Width  Length1  Length2  Length3
139         4    Pike   770.0    7.68  5.376     44.8     48.0     51.2

In [38]:
X_new = df_new[['Height', 'Width', 'Length1', 'Length2', 'Length3']]

In [39]:
X_new.shape

(1, 5)

In [40]:
y_pred_new = model.predict(X_new)

In [42]:
y_pred_new

array([894.39776737])